version: "3.6"

services:
  db:
    image: postgis/postgis:12-2.5-alpine
    volumes:
      - ./pg:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=docker
  redmin:
    image: redmine:4.1.1-alpine
    environment:
      - REDMINE_DB_POSTGRES=db
      - REDMINE_DB_USERNAME=postgres
      - REDMINE_DB_PASSWORD=docker
    volumes:
      - ./redmine_datadir:/usr/src/redmine/files
    links:
      - "db:db"
  nginx_dev:
    build:
      context: nginx
      target: base
    volumes:
      - ./logs:/logs
    links:
      - "redmin:redmin"
    ports:
      - "80:80"
  nginx:
    build:
      context: nginx
      target: prod
    links:
      - "redmin:redmin"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs:/logs
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    env_file:
      - nginx.env
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  check_db:
    image: schaffdev/port_check:latest
    environment:
      - CHECK_HOST=db
      - CHECK_PORT=5432
  check_redmin:
    image: schaffdev/port_check
    environment:
      - CHECK_HOST=redmin
      - CHECK_PORT=3000

