version: "3.8"

services:
  db:
    image: postgis/postgis:12-2.5-alpine
    volumes:
      - ./pg:/var/lob/postgresql
    environment:
      - POSTGRES_PASSWORD=docker
  geoserver:
    image: kartoza/geoserver:2.18.0
    volumes:
      - ./geo:/opt/geoserver/data_dir
    environment:
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - TOMCAT_EXTRAS=false
      - STABLE_EXTENSIONS=importer-plugin
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/logs
    links:
      - "geoserver:geoserver"

